services:
  network-deploy-service:
     networks:
      - jovisco

  microservice-base-config:
    extends: 
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m

  microservice-business-services-config:
    extends:
      service: microservice-base-config
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://configserver:8071/
      - SPRING_PROFILE_ACTIVE=default

    