services:
  rabbit:
    image: rabbitmq:3.13-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-config.yml
      service: network-deploy-service

  configserver:
    image: "joheiss/sb3-configserver:v1"
    container_name: "jo_configserver"
    ports:
      - "8071:8071"
    depends_on:
      rabbit: 
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  accounts:
    image: "joheiss/sb3-accounts:v1"
    container_name: "jo_accounts"
    ports:
      - "8091:8091"
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      - SPRING_APPLICATION_NAME=accounts    
    extends:
      file: common-config.yml
      service: microservice-business-services-config

  loans:
    image: "joheiss/sb3-loans:v1"
    container_name: "jo_loans"
    ports:
      - "8092:8092"
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      - SPRING_APPLICATION_NAME=loans    
    extends:
      file: common-config.yml
      service: microservice-business-services-config

  cards:
    image: "joheiss/sb3-cards:v1"
    container_name: "jo_cards"
    ports:
      - "8093:8093"
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      - SPRING_APPLICATION_NAME=cards
    extends:
      file: common-config.yml
      service: microservice-business-services-config

networks:
  jovisco:
    driver: "bridge"

