services:
    # accountsdb:
    #   container_name: accountsdb
    #   ports:
    #     - "3306:3306"
    #   environment:
    #     - MYSQL_DATABASE=accountsdb
    #   extends:
    #     file: common-config.yml
    #     service: microservice-db-config

    # loansdb:
    #   container_name: loansdb
    #   ports:
    #     - "3307:3306"
    #   environment:
    #     - MYSQL_DATABASE=loansdb
    #   extends:
    #     file: common-config.yml
    #     service: microservice-db-config

    # cardsdb:
    #   container_name: cardsdb
    #   ports:
    #     - "3308:3306"
    #   environment:
    #     - MYSQL_DATABASE=cardsdb
    #   extends:
    #     file: common-config.yml
    #     service: microservice-db-config

    rabbit:
        image: rabbitmq:3.13-management
        hostname: rabbitmq
        ports:
            - '5672:5672'
            - '15672:15672'
        healthcheck:
            test: rabbitmq-diagnostics check_port_connectivity
            interval: 10s
            timeout: 5s
            retries: 10
            start_period: 5s
        extends:
            file: common-config.yml
            service: network-deploy-service

    configserver:
        image: 'joheiss/sb3-configserver:v3'
        container_name: 'jo_configserver'
        ports:
            - '8071:8071'
        depends_on:
            rabbit:
                condition: service_healthy
        healthcheck:
            test: 'curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1'
            interval: 10s
            timeout: 10s
            retries: 10
            start_period: 10s
        extends:
            file: common-config.yml
            service: microservice-base-config

    eurekaserver:
        image: 'joheiss/sb3-eurekaserver:v4'
        container_name: 'jo_eurekaserver'
        ports:
            - '8070:8070'
        depends_on:
            configserver:
                condition: service_healthy
        healthcheck:
            test: 'curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1'
            interval: 10s
            timeout: 10s
            retries: 10
            start_period: 10s
        environment:
            SPRING_APPLICATION_NAME: eurekaserver
        extends:
            file: common-config.yml
            service: microservice-eureka-config

    accounts:
        image: 'joheiss/sb3-accounts:v5.1'
        container_name: 'jo_accounts'
        ports:
            - '8091:8091'
        healthcheck:
          test: "curl --fail --silent localhost:8091/actuator/health/readiness | grep UP || exit 1"
          interval: 10s
          timeout: 5s
          retries: 10
          start_period: 10s
        depends_on:
            eurekaserver:
                condition: service_healthy
            accountsdb:
                condition: service_healthy
        environment:
            SPRING_APPLICATION_NAME: accounts
            SPRING_DATASOURCE_URL: 'jdbc:mysql://accountsdb:3306/accountsdb'
        extends:
            file: common-config.yml
            service: microservice-business-services-config

    loans:
        image: 'joheiss/sb3-loans:v5.1'
        container_name: 'jo_loans'
        ports:
            - '8092:8092'
        healthcheck:
          test: "curl --fail --silent localhost:8092/actuator/health/readiness | grep UP || exit 1"
          interval: 10s
          timeout: 5s
          retries: 10
          start_period: 10s

        depends_on:
            eurekaserver:
                condition: service_healthy
            loansdb:
                condition: service_healthy
        environment:
            SPRING_APPLICATION_NAME: loans
            SPRING_DATASOURCE_URL: 'jdbc:mysql://loansdb:3306/loansdb'
        extends:
            file: common-config.yml
            service: microservice-business-services-config

    cards:
        image: 'joheiss/sb3-cards:v5.1'
        container_name: 'jo_cards'
        ports:
            - '8093:8093'
        healthcheck:
          test: "curl --fail --silent localhost:8093/actuator/health/readiness | grep UP || exit 1"
          interval: 10s
          timeout: 5s
          retries: 10
          start_period: 10s
        depends_on:
            eurekaserver:
                condition: service_healthy
            cardsdb:
                condition: service_healthy
        environment:
            SPRING_APPLICATION_NAME: cards
            SPRING_DATASOURCE_URL: 'jdbc:mysql://cardsdb:3306/cardsdb'
        extends:
            file: common-config.yml
            service: microservice-business-services-config
            
    gatewayserver:
      image: "joheiss/sb3-gatewayserver:v5.1"
      container_name: jo_gatewayserver
      ports:
        - "8072:8072"
      depends_on:
        accounts:
          condition: service_healthy
        loans:
          condition: service_healthy
        cards:
          condition: service_healthy
      environment:
        SPRING_APPLICATION_NAME: gatewayserver
      extends:
        file: common-config.yml
        service: microservice-business-services-config


networks:
    jovisco:
        driver: 'bridge'
