services:
    network-deploy-service:
        networks:
            - jovisco

    microservice-db-config:
        extends:
            service: network-deploy-service
        image: mysql
        healthcheck:
            test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
            interval: 10s
            timeout: 10s
            retries: 10
            start_period: 10s
        environment:
            - MYSQL_ROOT_PASSWORD=root

    microservice-base-config:
        extends:
            service: network-deploy-service
        deploy:
            resources:
                limits:
                    memory: 700m
        environment:
            SPRING_RABBITMQ_HOST: rabbit

    microservice-eureka-config:
        extends:
            service: microservice-base-config
        environment:
            SPRING_CONFIG_IMPORT: 'configserver:http://configserver:8071/'

    microservice-business-services-config:
        extends:
            service: microservice-eureka-config
        environment:
            EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: 'http://eurekaserver:8070/eureka/'
            SPRING_PROFILES_ACTIVE: prod
            SPRING_DATASOURCE_USERNAME: root
            SPRING_DATASOURCE_PASSWORD: root
